Wdp211101 9
odevpl/wdp-2111-01 pull request #15
Opened 2021-11-05 14:49 UTC by NatanDopieralski

2021-11-05 21:00 UTC, odevpl approved these changes

2021-11-05 21:01 UTC, odevpl requested changes
Pojawiło się sporo konfliktów. Napraw je proszę

2021-11-09 17:17 UTC, AdrianSadowski requested changes
Wchodząc w plik stylów kod od hover jest mało czytelny. 
W settings.scss dodał bym placeholder `$actionDuration: 250ms;`
A w pliku styli `transition: $actionDuration` 
Myślę, że dzięki temu kod będzie bardziej czytelniejszy dla innych i nie będzie trzeba specjalnie wchodzić w plik settings aby wiedzieć co się dzieje na :hover. 

Brakuje nam części zadania odpowiadającej za animacje, którymi klient miał by eksperymentować z efektami hover. (obrócenie, przesunięcie elementu)

Nie zastosowałeś transition na niektórych elementach. np. komponencie NewFurniture po najechaniu na obrazek pojawiają się nam 2 przyciski, podobnie jest w komponencie Promition

W skrócie:
-zmiana placeholdera na bardziej czytelny
-dokończenie 2 częsci zadania
-dodanie efektów hover na pozostałych elementach które je nie maja.

2021-11-09 17:46 UTC, AdrianSadowski commented
Do sprawdzania czy wszystkie elementy :hover maja transition polecam zmienić je na 1s lub więcej.
Znalazłem jeszcze brakujące hover na elementach: 
-Pasek z wyborem kategorii
-kropki w komponencie Promotion
-cena w komponencie Promotion
-hover po najechaniu na zdjęcie w Promotion
-elementy w komponencie FeaturesBoxes
-lista kategorii w komponencie NewFurniture
-cena oraz buttony 'Quick Viev' oraz 'ADD to CARD'

2021-11-10 06:53 UTC, merged