subpage/blog
odevpl/wdp-2111-01 pull request #36
Opened 2021-11-12 16:53 UTC by HatedAlex

2021-11-14 13:33 UTC, PaulinaPodraza approved these changes
1.
![image](https://user-images.githubusercontent.com/80419830/141682921-b5fe41bc-fc18-4a77-8aa1-c48153e24844.png)

Sekcja 'Blog_menu' nachodzi na sekcję z postami, więc to wymagało by poprawy.  

2. 
![image](https://user-images.githubusercontent.com/80419830/141683121-fa044882-f96d-4c00-b267-cee0cf179a25.png)

Linki do postów w 'Blog_menu' zrobiłabym w czarnym kolorze tak jak pozostałe linki np. w kategoriach albo archiwum, wydaje mi się, że tak też jest na wizualizacji. 

Poza tym wygląda super :) 
P.S. zaciągnęłam przykładowe zdjęcia, ponieważ nie mogłam znaleźć tych które Ty dołączyłaś.

2021-11-15 09:21 UTC, odevpl requested changes
Skoro ticket nie działa jak powinien, dlaczego Approve?

Popraw proszę wyświetlanie.

2021-11-16 20:28 UTC, PaulinaPodraza requested changes
Rozwiąż proszę konflikty.

2021-11-16 20:52 UTC, PaulinaPodraza reviewed
Poza tym wygląda super :)

2021-11-17 15:34 UTC, PaulinaPodraza approved these changes

2021-11-17 20:52 UTC, merged

2021-11-17 22:08 UTC, michalik-maciej commented
Czy tylko ja mam problem z paczką @material-ui/core po zmergowaniu bloga do mastera? 
./node_modules/@material-ui/core/Accordion/Accordion.js
Module not found: Can't resolve 'react/jsx-runtime' in 'C:\Users\macie\OneDrive\_html css js\Kodilla\modul_24_team\node_modules\@material-ui\core\Accordion'